Added conditional check in bubble sort.
caspervonb/toneofsorting pull request #6
Opened 2017-11-04 14:12 UTC by rupav

To avoid iterating even after sorting.

2017-11-05 12:18 UTC, caspervonb requested changes
A few minor nitpicks, code could be leaner.

2017-11-05 12:48 UTC, rupav commented
@caspervonb changed as requested. But I am not able to align properly the changes,
I am changing code on sublineText 3 which shows correct alignment,
but then after
`git push -f origin` , alignment gets disturbed.
What to do here?

2017-11-05 15:51 UTC, caspervonb commented
@rupav Looks like you have a mix of tabs and spaces! e.g start of line https://github.com/rupav/toneofsorting/blob/10be93847bb204ce8035ebfee70c36fd75511718/sort.js#L19 actually contains two spaces and one tab.

2017-11-05 15:52 UTC, caspervonb requested changes
Replace tabs with spaces.

2017-11-05 15:52 UTC, caspervonb commented on sort.js
> +  	sorted = true;
This line contains tabs

2017-11-05 15:52 UTC, caspervonb commented on sort.js
> +	sorted = false;
This line contains tabs.

2017-11-06 02:26 UTC, rupav commented
@caspervonb replacing 'tabs' with spaces worked fine.
Now its correct.
Can you tell me why tabs create problems?
Thanks :)

2017-11-07 11:33 UTC, caspervonb approved these changes

2017-11-08 19:15 UTC, caspervonb commented
@rupav tabs don't have a set display size, so a tab can represent anywhere from 1-N spaces and different viewers (editors) have different settings.

Thanks, will merge in later ;)

2017-11-08 19:26 UTC, rupav commented
Ok, thanks. :)

2017-11-09 12:07 UTC, merged